# Site settings
title: Digital Rain Modern C++ Project Blog
author:
  name: Michelle Lynch
  email: your-email@domain.com
description: "A blog."

# Build settings
remote_theme: pages-themes/slate@v0.2.0
