# Site settings
title: Digital Rain Modern C++ Project Blog
author:
  name: Olamide Aderogba
  email: g00401971@atu.ie
description: "C++ Programming project."

# Build settings
remote_theme: jekyll/minima
