# Site settings
title: Olamide's Blog

author:
  name: Olamide Aderogba
  email: G00401971@atu.ie
description: "A website."

# Build settings
remote_theme: "pmarsceill/just-the-docs"

plugins:
  - jekyll-remote-theme

