# Site settings
title: Olamide's Blog
author:
  name: Olamide Aderogba
  email: G00401971@atu.ie
description: "A website."

# Build settings
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme
